id = "asp-classic"
name = "ASP Classic"
version = "0.1.0"
schema_version = 1
authors = ["Hendry Muda Rangkuti <hendrymudarkt@gmail.com>"]
description = "ASP Classic (VBScript) syntax highlighting for Zed"
repository = "https://github.com/hendrymudarkt/zed-asp-classic"

[grammars.asp_classic]
repository = "https://github.com/hendrymudarkt/tree-sitter-asp-classic"
rev = "e9e273191472ed628d70ccd4f4a23ae2ab730906"
