id = "asp-classic"
name = "ASP Classic"
version = "0.1.0"
schema_version = 1
authors = ["Hendry Muda Rangkuti <hendrymudarkt@gmail.com>"]
description = "ASP Classic (VBScript) syntax highlighting for Zed"
repository = "https://github.com/hendrymudarkt/zed-asp-classic"

[grammars.asp_classic]
repository = "https://github.com/hendrymudarkt/tree-sitter-asp-classic"
rev = "9a60b18bdba38349765aa3bfda9f3108a68e7639"
