name = "ASP Classic"
grammar = "asp_classic"
path_suffixes = ["asp", "asa"]
line_comments = ["' "]
block_comment = ["<!--", " -->"]
first_line_pattern = "<%@\\s*(?i:language)\\s*=\\s*[\"']?(?i:vbscript|jscript)"
autoclose_before = ")]}"
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
